apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-deployer.fullname" . }}-jobs
  labels:
    {{- include "k8s-deployer.labels" . | nindent 4 }}
data:
  jobs.yaml: |
    {{- dict "timezone" .Values.timezone "jobs" .Values.jobs | toYaml | nindent 4 }}
