{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deployer.postgresqlName" . }}
  labels:
    {{- include "k8s-deployer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "k8s-deployer.postgresqlSelectorLabels" . | nindent 4 }}
{{- end }}
